services:
  cab-user:
    image: iraianbu/kafka-cab-book-user
    container_name: cab-user
    depends_on:
      - kafka
      - zookeeper
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka
    networks:
      - kafka-net

  cab-driver:
    image: iraianbu/kafka-cab-book-driver
    container_name: cab-driver
    ports:
      - "8081:8081"
    depends_on:
      - kafka
      - zookeeper
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka
    networks:
      - kafka-net

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    environment:
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "22181:2181"
    networks:
      - kafka-net

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
    networks:
      - kafka-net

networks:
  kafka-net:
    driver: bridge
